language: java

jdk:
  - oraclejdk8

env:
  - DB=h2 JDBC_URL= JDBC_USER= JDBC_PASSWORD=
  - DB=hsqldb JDBC_URL=jdbc:hsqldb:mem:it JDBC_USER=sa JDBC_PASSWORD=

script: 
  - ./gradlew check -info -PjdbcUrl=$JDBC_URL -PjdbcUser=$JDBC_USER -PjdbcPassword=$JDBC_PASSWORD